server.port: 80
#spring.profiles: default
demo.security.jwt:
  tokenExpirationTime: 43200 # 30 day
  refreshTokenExpTime: 86400 # 60 day
  tokenIssuer: http://svlada.com
  tokenSigningKey: xm8EV6Hy5RMFK4EEACIDAwQus

tomcatPath: C:\Users\Public\pic
spring:
  application:
      name: oauth2-client
  datasource: #数据源的配置
    url: jdbc:mysql://120.77.215.74:3306/weixin_dev?useUnicode=true&characterEncoding=UTF-8
    username: root
    password: test
  mvc:
        static-path-pattern: /**
  resources:
        static-locations: classpath:/META-INF/resources/,classpath:/resources/,classpath:/static/,classpath:/public/,file:${tomcatPath}

  jpa: #jpa的支持：hibernate的相关配置
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    database: MYSQL
    openInView: true
    show_sql: true
    generate-ddl: true #(false)
    hibernate:
        ddl-auto: update
#  http:
#    multipart:
#      enabled: false
#      max-file-size: 20MB
#      max-request-size: 10MB
#spring:
#  http:
#    multipart:
#      enabled: false
#spring.datasource:
#  url: "jdbc:h2:mem:testdb"
#  driverClassName: org.h2.Driver
#  username: sa
#  password: ""
#  data: "classpath*:data.sql"
#spring.jpa:
#  database-platform: org.hibernate.dialect.H2Dialect
#spring.h2.console.enabled: true

